
    // "Global": {
    //     "NewConfirmed": 169788,
    //     "TotalConfirmed": 3657967,
    //     "NewDeaths": 10400,
    //     "TotalDeaths": 257061,
    //     "NewRecovered": 117168,
    //     "TotalRecovered": 1192286
    // },
 let data ={

    "Global": {
        "NewConfirmed": 169788,
        "TotalConfirmed": 3657967,
        "NewDeaths": 10400,
        "TotalDeaths": 257061,
        "NewRecovered": 117168,
        "TotalRecovered": 1192286
    },
    "Countries": [
        {
            "Country": "ALA Aland Islands",
            "CountryCode": "AX",
            "Slug": "ala-aland-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Afghanistan",
            "CountryCode": "AF",
            "Slug": "afghanistan",
            "NewConfirmed": 330,
            "TotalConfirmed": 3224,
            "NewDeaths": 5,
            "TotalDeaths": 95,
            "NewRecovered": 24,
            "TotalRecovered": 421,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Albania",
            "CountryCode": "AL",
            "Slug": "albania",
            "NewConfirmed": 17,
            "TotalConfirmed": 820,
            "NewDeaths": 0,
            "TotalDeaths": 31,
            "NewRecovered": 27,
            "TotalRecovered": 570,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Algeria",
            "CountryCode": "DZ",
            "Slug": "algeria",
            "NewConfirmed": 190,
            "TotalConfirmed": 4838,
            "NewDeaths": 5,
            "TotalDeaths": 470,
            "NewRecovered": 69,
            "TotalRecovered": 2067,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "American Samoa",
            "CountryCode": "AS",
            "Slug": "american-samoa",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Andorra",
            "CountryCode": "AD",
            "Slug": "andorra",
            "NewConfirmed": 1,
            "TotalConfirmed": 751,
            "NewDeaths": 1,
            "TotalDeaths": 46,
            "NewRecovered": 15,
            "TotalRecovered": 514,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Angola",
            "CountryCode": "AO",
            "Slug": "angola",
            "NewConfirmed": 1,
            "TotalConfirmed": 36,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 11,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Anguilla",
            "CountryCode": "AI",
            "Slug": "anguilla",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Antarctica",
            "CountryCode": "AQ",
            "Slug": "antarctica",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Antigua and Barbuda",
            "CountryCode": "AG",
            "Slug": "antigua-and-barbuda",
            "NewConfirmed": 0,
            "TotalConfirmed": 25,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 1,
            "TotalRecovered": 16,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Argentina",
            "CountryCode": "AR",
            "Slug": "argentina",
            "NewConfirmed": 133,
            "TotalConfirmed": 5020,
            "NewDeaths": 4,
            "TotalDeaths": 264,
            "NewRecovered": 30,
            "TotalRecovered": 1472,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Armenia",
            "CountryCode": "AM",
            "Slug": "armenia",
            "NewConfirmed": 112,
            "TotalConfirmed": 2619,
            "NewDeaths": 1,
            "TotalDeaths": 40,
            "NewRecovered": 40,
            "TotalRecovered": 1111,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Aruba",
            "CountryCode": "AW",
            "Slug": "aruba",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Australia",
            "CountryCode": "AU",
            "Slug": "australia",
            "NewConfirmed": 6875,
            "TotalConfirmed": 6875,
            "NewDeaths": 97,
            "TotalDeaths": 97,
            "NewRecovered": 5975,
            "TotalRecovered": 5975,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Austria",
            "CountryCode": "AT",
            "Slug": "austria",
            "NewConfirmed": 29,
            "TotalConfirmed": 15650,
            "NewDeaths": 6,
            "TotalDeaths": 606,
            "NewRecovered": 146,
            "TotalRecovered": 13462,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Azerbaijan",
            "CountryCode": "AZ",
            "Slug": "azerbaijan",
            "NewConfirmed": 76,
            "TotalConfirmed": 2060,
            "NewDeaths": 0,
            "TotalDeaths": 26,
            "NewRecovered": 28,
            "TotalRecovered": 1508,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bahamas",
            "CountryCode": "BS",
            "Slug": "bahamas",
            "NewConfirmed": 6,
            "TotalConfirmed": 89,
            "NewDeaths": 0,
            "TotalDeaths": 11,
            "NewRecovered": 1,
            "TotalRecovered": 26,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bahrain",
            "CountryCode": "BH",
            "Slug": "bahrain",
            "NewConfirmed": 187,
            "TotalConfirmed": 3720,
            "NewDeaths": 0,
            "TotalDeaths": 8,
            "NewRecovered": 18,
            "TotalRecovered": 1762,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bangladesh",
            "CountryCode": "BD",
            "Slug": "bangladesh",
            "NewConfirmed": 786,
            "TotalConfirmed": 10929,
            "NewDeaths": 1,
            "TotalDeaths": 183,
            "NewRecovered": 194,
            "TotalRecovered": 1403,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Barbados",
            "CountryCode": "BB",
            "Slug": "barbados",
            "NewConfirmed": 0,
            "TotalConfirmed": 82,
            "NewDeaths": 0,
            "TotalDeaths": 7,
            "NewRecovered": 1,
            "TotalRecovered": 47,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Belarus",
            "CountryCode": "BY",
            "Slug": "belarus",
            "NewConfirmed": 861,
            "TotalConfirmed": 18350,
            "NewDeaths": 4,
            "TotalDeaths": 107,
            "NewRecovered": 512,
            "TotalRecovered": 3771,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Belgium",
            "CountryCode": "BE",
            "Slug": "belgium",
            "NewConfirmed": 242,
            "TotalConfirmed": 50509,
            "NewDeaths": 92,
            "TotalDeaths": 8016,
            "NewRecovered": 63,
            "TotalRecovered": 12441,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Belize",
            "CountryCode": "BZ",
            "Slug": "belize",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 2,
            "TotalRecovered": 16,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Benin",
            "CountryCode": "BJ",
            "Slug": "benin",
            "NewConfirmed": 0,
            "TotalConfirmed": 96,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 50,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bermuda",
            "CountryCode": "BM",
            "Slug": "bermuda",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bhutan",
            "CountryCode": "BT",
            "Slug": "bhutan",
            "NewConfirmed": 0,
            "TotalConfirmed": 7,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 5,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bolivia",
            "CountryCode": "BO",
            "Slug": "bolivia",
            "NewConfirmed": 121,
            "TotalConfirmed": 1802,
            "NewDeaths": 4,
            "TotalDeaths": 86,
            "NewRecovered": 13,
            "TotalRecovered": 187,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bosnia and Herzegovina",
            "CountryCode": "BA",
            "Slug": "bosnia-and-herzegovina",
            "NewConfirmed": 20,
            "TotalConfirmed": 1946,
            "NewDeaths": 1,
            "TotalDeaths": 79,
            "NewRecovered": 56,
            "TotalRecovered": 911,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Botswana",
            "CountryCode": "BW",
            "Slug": "botswana",
            "NewConfirmed": 0,
            "TotalConfirmed": 23,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 8,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bouvet Island",
            "CountryCode": "BV",
            "Slug": "bouvet-island",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Brazil",
            "CountryCode": "BR",
            "Slug": "brazil",
            "NewConfirmed": 6835,
            "TotalConfirmed": 115455,
            "NewDeaths": 571,
            "TotalDeaths": 7938,
            "NewRecovered": 2406,
            "TotalRecovered": 48221,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "British Indian Ocean Territory",
            "CountryCode": "IO",
            "Slug": "british-indian-ocean-territory",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "British Virgin Islands",
            "CountryCode": "VG",
            "Slug": "british-virgin-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Brunei Darussalam",
            "CountryCode": "BN",
            "Slug": "brunei",
            "NewConfirmed": 0,
            "TotalConfirmed": 138,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 1,
            "TotalRecovered": 131,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Bulgaria",
            "CountryCode": "BG",
            "Slug": "bulgaria",
            "NewConfirmed": 52,
            "TotalConfirmed": 1704,
            "NewDeaths": 2,
            "TotalDeaths": 80,
            "NewRecovered": 21,
            "TotalRecovered": 342,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Burkina Faso",
            "CountryCode": "BF",
            "Slug": "burkina-faso",
            "NewConfirmed": 16,
            "TotalConfirmed": 688,
            "NewDeaths": 2,
            "TotalDeaths": 48,
            "NewRecovered": 3,
            "TotalRecovered": 548,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Burundi",
            "CountryCode": "BI",
            "Slug": "burundi",
            "NewConfirmed": 0,
            "TotalConfirmed": 15,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 7,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cambodia",
            "CountryCode": "KH",
            "Slug": "cambodia",
            "NewConfirmed": 0,
            "TotalConfirmed": 122,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 120,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cameroon",
            "CountryCode": "CM",
            "Slug": "cameroon",
            "NewConfirmed": 0,
            "TotalConfirmed": 2104,
            "NewDeaths": 0,
            "TotalDeaths": 64,
            "NewRecovered": 0,
            "TotalRecovered": 953,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Canada",
            "CountryCode": "CA",
            "Slug": "canada",
            "NewConfirmed": 1245,
            "TotalConfirmed": 63201,
            "NewDeaths": 187,
            "TotalDeaths": 4189,
            "NewRecovered": 0,
            "TotalRecovered": 26030,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cape Verde",
            "CountryCode": "CV",
            "Slug": "cape-verde",
            "NewConfirmed": 11,
            "TotalConfirmed": 186,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 0,
            "TotalRecovered": 37,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cayman Islands",
            "CountryCode": "KY",
            "Slug": "cayman-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Central African Republic",
            "CountryCode": "CF",
            "Slug": "central-african-republic",
            "NewConfirmed": 0,
            "TotalConfirmed": 85,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 10,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Chad",
            "CountryCode": "TD",
            "Slug": "chad",
            "NewConfirmed": 53,
            "TotalConfirmed": 170,
            "NewDeaths": 7,
            "TotalDeaths": 17,
            "NewRecovered": 4,
            "TotalRecovered": 43,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Chile",
            "CountryCode": "CL",
            "Slug": "chile",
            "NewConfirmed": 1373,
            "TotalConfirmed": 22016,
            "NewDeaths": 5,
            "TotalDeaths": 275,
            "NewRecovered": 295,
            "TotalRecovered": 10710,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "China",
            "CountryCode": "CN",
            "Slug": "china",
            "NewConfirmed": 83966,
            "TotalConfirmed": 83966,
            "NewDeaths": 4637,
            "TotalDeaths": 4637,
            "NewRecovered": 78857,
            "TotalRecovered": 78857,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Christmas Island",
            "CountryCode": "CX",
            "Slug": "christmas-island",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cocos (Keeling) Islands",
            "CountryCode": "CC",
            "Slug": "cocos-keeling-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Colombia",
            "CountryCode": "CO",
            "Slug": "colombia",
            "NewConfirmed": 640,
            "TotalConfirmed": 8613,
            "NewDeaths": 20,
            "TotalDeaths": 378,
            "NewRecovered": 206,
            "TotalRecovered": 2013,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Comoros",
            "CountryCode": "KM",
            "Slug": "comoros",
            "NewConfirmed": 0,
            "TotalConfirmed": 3,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Congo (Brazzaville)",
            "CountryCode": "CG",
            "Slug": "congo-brazzaville",
            "NewConfirmed": 0,
            "TotalConfirmed": 236,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 26,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Congo (Kinshasa)",
            "CountryCode": "CD",
            "Slug": "congo-kinshasa",
            "NewConfirmed": 23,
            "TotalConfirmed": 705,
            "NewDeaths": 0,
            "TotalDeaths": 34,
            "NewRecovered": 10,
            "TotalRecovered": 90,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cook Islands",
            "CountryCode": "CK",
            "Slug": "cook-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Costa Rica",
            "CountryCode": "CR",
            "Slug": "costa-rica",
            "NewConfirmed": 13,
            "TotalConfirmed": 755,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 14,
            "TotalRecovered": 413,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Croatia",
            "CountryCode": "HR",
            "Slug": "croatia",
            "NewConfirmed": 11,
            "TotalConfirmed": 2112,
            "NewDeaths": 3,
            "TotalDeaths": 83,
            "NewRecovered": 38,
            "TotalRecovered": 1560,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cuba",
            "CountryCode": "CU",
            "Slug": "cuba",
            "NewConfirmed": 17,
            "TotalConfirmed": 1685,
            "NewDeaths": 0,
            "TotalDeaths": 69,
            "NewRecovered": 78,
            "TotalRecovered": 954,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Cyprus",
            "CountryCode": "CY",
            "Slug": "cyprus",
            "NewConfirmed": 4,
            "TotalConfirmed": 878,
            "NewDeaths": 0,
            "TotalDeaths": 15,
            "NewRecovered": 0,
            "TotalRecovered": 296,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Czech Republic",
            "CountryCode": "CZ",
            "Slug": "czech-republic",
            "NewConfirmed": 77,
            "TotalConfirmed": 7896,
            "NewDeaths": 5,
            "TotalDeaths": 257,
            "NewRecovered": 199,
            "TotalRecovered": 4006,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Côte d'Ivoire",
            "CountryCode": "CI",
            "Slug": "cote-divoire",
            "NewConfirmed": 32,
            "TotalConfirmed": 1464,
            "NewDeaths": 1,
            "TotalDeaths": 18,
            "NewRecovered": 8,
            "TotalRecovered": 701,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Denmark",
            "CountryCode": "DK",
            "Slug": "denmark",
            "NewConfirmed": 151,
            "TotalConfirmed": 9821,
            "NewDeaths": 10,
            "TotalDeaths": 503,
            "NewRecovered": 208,
            "TotalRecovered": 7296,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Djibouti",
            "CountryCode": "DJ",
            "Slug": "djibouti",
            "NewConfirmed": 4,
            "TotalConfirmed": 1120,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 32,
            "TotalRecovered": 745,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Dominica",
            "CountryCode": "DM",
            "Slug": "dominica",
            "NewConfirmed": 0,
            "TotalConfirmed": 16,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 1,
            "TotalRecovered": 14,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Dominican Republic",
            "CountryCode": "DO",
            "Slug": "dominican-republic",
            "NewConfirmed": 245,
            "TotalConfirmed": 8480,
            "NewDeaths": 8,
            "TotalDeaths": 354,
            "NewRecovered": 134,
            "TotalRecovered": 1905,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Ecuador",
            "CountryCode": "EC",
            "Slug": "ecuador",
            "NewConfirmed": 0,
            "TotalConfirmed": 31881,
            "NewDeaths": 0,
            "TotalDeaths": 1569,
            "NewRecovered": 0,
            "TotalRecovered": 3433,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Egypt",
            "CountryCode": "EG",
            "Slug": "egypt",
            "NewConfirmed": 388,
            "TotalConfirmed": 7201,
            "NewDeaths": 16,
            "TotalDeaths": 452,
            "NewRecovered": 98,
            "TotalRecovered": 1730,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "El Salvador",
            "CountryCode": "SV",
            "Slug": "el-salvador",
            "NewConfirmed": 32,
            "TotalConfirmed": 587,
            "NewDeaths": 1,
            "TotalDeaths": 14,
            "NewRecovered": 25,
            "TotalRecovered": 205,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Equatorial Guinea",
            "CountryCode": "GQ",
            "Slug": "equatorial-guinea",
            "NewConfirmed": 0,
            "TotalConfirmed": 315,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 13,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Eritrea",
            "CountryCode": "ER",
            "Slug": "eritrea",
            "NewConfirmed": 0,
            "TotalConfirmed": 39,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 4,
            "TotalRecovered": 30,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Estonia",
            "CountryCode": "EE",
            "Slug": "estonia",
            "NewConfirmed": 8,
            "TotalConfirmed": 1711,
            "NewDeaths": 0,
            "TotalDeaths": 55,
            "NewRecovered": 2,
            "TotalRecovered": 261,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Ethiopia",
            "CountryCode": "ET",
            "Slug": "ethiopia",
            "NewConfirmed": 5,
            "TotalConfirmed": 145,
            "NewDeaths": 1,
            "TotalDeaths": 4,
            "NewRecovered": 16,
            "TotalRecovered": 91,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Falkland Islands (Malvinas)",
            "CountryCode": "FK",
            "Slug": "falkland-islands-malvinas",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Faroe Islands",
            "CountryCode": "FO",
            "Slug": "faroe-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Fiji",
            "CountryCode": "FJ",
            "Slug": "fiji",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 14,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Finland",
            "CountryCode": "FI",
            "Slug": "finland",
            "NewConfirmed": 85,
            "TotalConfirmed": 5412,
            "NewDeaths": 6,
            "TotalDeaths": 246,
            "NewRecovered": 0,
            "TotalRecovered": 3500,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "France",
            "CountryCode": "FR",
            "Slug": "france",
            "NewConfirmed": 1049,
            "TotalConfirmed": 168935,
            "NewDeaths": 330,
            "TotalDeaths": 25498,
            "NewRecovered": 1365,
            "TotalRecovered": 51803,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "French Guiana",
            "CountryCode": "GF",
            "Slug": "french-guiana",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "French Polynesia",
            "CountryCode": "PF",
            "Slug": "french-polynesia",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "French Southern Territories",
            "CountryCode": "TF",
            "Slug": "french-southern-territories",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Gabon",
            "CountryCode": "GA",
            "Slug": "gabon",
            "NewConfirmed": 30,
            "TotalConfirmed": 397,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 0,
            "TotalRecovered": 93,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Gambia",
            "CountryCode": "GM",
            "Slug": "gambia",
            "NewConfirmed": 0,
            "TotalConfirmed": 17,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 9,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Georgia",
            "CountryCode": "GE",
            "Slug": "georgia",
            "NewConfirmed": 11,
            "TotalConfirmed": 604,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 17,
            "TotalRecovered": 240,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Germany",
            "CountryCode": "DE",
            "Slug": "germany",
            "NewConfirmed": 855,
            "TotalConfirmed": 167007,
            "NewDeaths": 0,
            "TotalDeaths": 6993,
            "NewRecovered": 2400,
            "TotalRecovered": 135100,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Ghana",
            "CountryCode": "GH",
            "Slug": "ghana",
            "NewConfirmed": 0,
            "TotalConfirmed": 2719,
            "NewDeaths": 0,
            "TotalDeaths": 18,
            "NewRecovered": 0,
            "TotalRecovered": 294,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Gibraltar",
            "CountryCode": "GI",
            "Slug": "gibraltar",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Greece",
            "CountryCode": "GR",
            "Slug": "greece",
            "NewConfirmed": 10,
            "TotalConfirmed": 2642,
            "NewDeaths": 0,
            "TotalDeaths": 146,
            "NewRecovered": 0,
            "TotalRecovered": 1374,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Greenland",
            "CountryCode": "GL",
            "Slug": "greenland",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Grenada",
            "CountryCode": "GD",
            "Slug": "grenada",
            "NewConfirmed": 0,
            "TotalConfirmed": 21,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 13,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guadeloupe",
            "CountryCode": "GP",
            "Slug": "guadeloupe",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guam",
            "CountryCode": "GU",
            "Slug": "guam",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guatemala",
            "CountryCode": "GT",
            "Slug": "guatemala",
            "NewConfirmed": 0,
            "TotalConfirmed": 730,
            "NewDeaths": 0,
            "TotalDeaths": 19,
            "NewRecovered": 0,
            "TotalRecovered": 79,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guernsey",
            "CountryCode": "GG",
            "Slug": "guernsey",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guinea",
            "CountryCode": "GN",
            "Slug": "guinea",
            "NewConfirmed": 101,
            "TotalConfirmed": 1811,
            "NewDeaths": 1,
            "TotalDeaths": 10,
            "NewRecovered": 48,
            "TotalRecovered": 498,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guinea-Bissau",
            "CountryCode": "GW",
            "Slug": "guinea-bissau",
            "NewConfirmed": 0,
            "TotalConfirmed": 413,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 19,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Guyana",
            "CountryCode": "GY",
            "Slug": "guyana",
            "NewConfirmed": 0,
            "TotalConfirmed": 92,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 0,
            "TotalRecovered": 27,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Haiti",
            "CountryCode": "HT",
            "Slug": "haiti",
            "NewConfirmed": 1,
            "TotalConfirmed": 101,
            "NewDeaths": 1,
            "TotalDeaths": 12,
            "NewRecovered": 0,
            "TotalRecovered": 10,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Heard and Mcdonald Islands",
            "CountryCode": "HM",
            "Slug": "heard-and-mcdonald-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Holy See (Vatican City State)",
            "CountryCode": "VA",
            "Slug": "holy-see-vatican-city-state",
            "NewConfirmed": 0,
            "TotalConfirmed": 11,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 2,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Honduras",
            "CountryCode": "HN",
            "Slug": "honduras",
            "NewConfirmed": 0,
            "TotalConfirmed": 1178,
            "NewDeaths": 0,
            "TotalDeaths": 83,
            "NewRecovered": 0,
            "TotalRecovered": 122,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Hong Kong, SAR China",
            "CountryCode": "HK",
            "Slug": "hong-kong-sar-china",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Hungary",
            "CountryCode": "HU",
            "Slug": "hungary",
            "NewConfirmed": 30,
            "TotalConfirmed": 3065,
            "NewDeaths": 12,
            "TotalDeaths": 363,
            "NewRecovered": 79,
            "TotalRecovered": 709,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Iceland",
            "CountryCode": "IS",
            "Slug": "iceland",
            "NewConfirmed": 0,
            "TotalConfirmed": 1799,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 10,
            "TotalRecovered": 1733,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "India",
            "CountryCode": "IN",
            "Slug": "india",
            "NewConfirmed": 2963,
            "TotalConfirmed": 49400,
            "NewDeaths": 127,
            "TotalDeaths": 1693,
            "NewRecovered": 1295,
            "TotalRecovered": 14142,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Indonesia",
            "CountryCode": "ID",
            "Slug": "indonesia",
            "NewConfirmed": 484,
            "TotalConfirmed": 12071,
            "NewDeaths": 8,
            "TotalDeaths": 872,
            "NewRecovered": 243,
            "TotalRecovered": 2197,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Iran, Islamic Republic of",
            "CountryCode": "IR",
            "Slug": "iran",
            "NewConfirmed": 1323,
            "TotalConfirmed": 99970,
            "NewDeaths": 63,
            "TotalDeaths": 6340,
            "NewRecovered": 1096,
            "TotalRecovered": 80475,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Iraq",
            "CountryCode": "IQ",
            "Slug": "iraq",
            "NewConfirmed": 85,
            "TotalConfirmed": 2431,
            "NewDeaths": 4,
            "TotalDeaths": 102,
            "NewRecovered": 27,
            "TotalRecovered": 1571,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Ireland",
            "CountryCode": "IE",
            "Slug": "ireland",
            "NewConfirmed": 211,
            "TotalConfirmed": 21983,
            "NewDeaths": 20,
            "TotalDeaths": 1339,
            "NewRecovered": 0,
            "TotalRecovered": 13386,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Isle of Man",
            "CountryCode": "IM",
            "Slug": "isle-of-man",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Israel",
            "CountryCode": "IL",
            "Slug": "israel",
            "NewConfirmed": 43,
            "TotalConfirmed": 16289,
            "NewDeaths": 3,
            "TotalDeaths": 238,
            "NewRecovered": 401,
            "TotalRecovered": 10465,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Italy",
            "CountryCode": "IT",
            "Slug": "italy",
            "NewConfirmed": 1075,
            "TotalConfirmed": 213013,
            "NewDeaths": 236,
            "TotalDeaths": 29315,
            "NewRecovered": 2352,
            "TotalRecovered": 85231,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Jamaica",
            "CountryCode": "JM",
            "Slug": "jamaica",
            "NewConfirmed": 2,
            "TotalConfirmed": 473,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 18,
            "TotalRecovered": 56,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Japan",
            "CountryCode": "JP",
            "Slug": "japan",
            "NewConfirmed": 175,
            "TotalConfirmed": 15253,
            "NewDeaths": 20,
            "TotalDeaths": 556,
            "NewRecovered": 340,
            "TotalRecovered": 4496,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Jersey",
            "CountryCode": "JE",
            "Slug": "jersey",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Jordan",
            "CountryCode": "JO",
            "Slug": "jordan",
            "NewConfirmed": 6,
            "TotalConfirmed": 471,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 5,
            "TotalRecovered": 375,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Kazakhstan",
            "CountryCode": "KZ",
            "Slug": "kazakhstan",
            "NewConfirmed": 156,
            "TotalConfirmed": 4205,
            "NewDeaths": 0,
            "TotalDeaths": 29,
            "NewRecovered": 106,
            "TotalRecovered": 1279,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Kenya",
            "CountryCode": "KE",
            "Slug": "kenya",
            "NewConfirmed": 45,
            "TotalConfirmed": 535,
            "NewDeaths": 0,
            "TotalDeaths": 24,
            "NewRecovered": 9,
            "TotalRecovered": 182,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Kiribati",
            "CountryCode": "KI",
            "Slug": "kiribati",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Korea (North)",
            "CountryCode": "KP",
            "Slug": "korea-north",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Korea (South)",
            "CountryCode": "KR",
            "Slug": "korea-south",
            "NewConfirmed": 2,
            "TotalConfirmed": 10806,
            "NewDeaths": 1,
            "TotalDeaths": 255,
            "NewRecovered": 50,
            "TotalRecovered": 9333,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Kuwait",
            "CountryCode": "KW",
            "Slug": "kuwait",
            "NewConfirmed": 526,
            "TotalConfirmed": 5804,
            "NewDeaths": 0,
            "TotalDeaths": 40,
            "NewRecovered": 85,
            "TotalRecovered": 2032,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Kyrgyzstan",
            "CountryCode": "KG",
            "Slug": "kyrgyzstan",
            "NewConfirmed": 13,
            "TotalConfirmed": 843,
            "NewDeaths": 1,
            "TotalDeaths": 11,
            "NewRecovered": 25,
            "TotalRecovered": 600,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Lao PDR",
            "CountryCode": "LA",
            "Slug": "lao-pdr",
            "NewConfirmed": 0,
            "TotalConfirmed": 19,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 9,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Latvia",
            "CountryCode": "LV",
            "Slug": "latvia",
            "NewConfirmed": 0,
            "TotalConfirmed": 896,
            "NewDeaths": 1,
            "TotalDeaths": 17,
            "NewRecovered": 0,
            "TotalRecovered": 348,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Lebanon",
            "CountryCode": "LB",
            "Slug": "lebanon",
            "NewConfirmed": 1,
            "TotalConfirmed": 741,
            "NewDeaths": 0,
            "TotalDeaths": 25,
            "NewRecovered": 6,
            "TotalRecovered": 206,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Lesotho",
            "CountryCode": "LS",
            "Slug": "lesotho",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Liberia",
            "CountryCode": "LR",
            "Slug": "liberia",
            "NewConfirmed": 4,
            "TotalConfirmed": 170,
            "NewDeaths": 2,
            "TotalDeaths": 20,
            "NewRecovered": 0,
            "TotalRecovered": 58,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Libya",
            "CountryCode": "LY",
            "Slug": "libya",
            "NewConfirmed": 0,
            "TotalConfirmed": 63,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 23,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Liechtenstein",
            "CountryCode": "LI",
            "Slug": "liechtenstein",
            "NewConfirmed": 0,
            "TotalConfirmed": 82,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 55,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Lithuania",
            "CountryCode": "LT",
            "Slug": "lithuania",
            "NewConfirmed": 4,
            "TotalConfirmed": 1423,
            "NewDeaths": 0,
            "TotalDeaths": 46,
            "NewRecovered": 40,
            "TotalRecovered": 678,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Luxembourg",
            "CountryCode": "LU",
            "Slug": "luxembourg",
            "NewConfirmed": 12,
            "TotalConfirmed": 3840,
            "NewDeaths": 0,
            "TotalDeaths": 96,
            "NewRecovered": 7,
            "TotalRecovered": 3412,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Macao, SAR China",
            "CountryCode": "MO",
            "Slug": "macao-sar-china",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Macedonia, Republic of",
            "CountryCode": "MK",
            "Slug": "macedonia",
            "NewConfirmed": 8,
            "TotalConfirmed": 1526,
            "NewDeaths": 1,
            "TotalDeaths": 86,
            "NewRecovered": 21,
            "TotalRecovered": 1013,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Madagascar",
            "CountryCode": "MG",
            "Slug": "madagascar",
            "NewConfirmed": 2,
            "TotalConfirmed": 151,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 2,
            "TotalRecovered": 101,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Malawi",
            "CountryCode": "MW",
            "Slug": "malawi",
            "NewConfirmed": 0,
            "TotalConfirmed": 41,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 9,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Malaysia",
            "CountryCode": "MY",
            "Slug": "malaysia",
            "NewConfirmed": 30,
            "TotalConfirmed": 6383,
            "NewDeaths": 1,
            "TotalDeaths": 106,
            "NewRecovered": 83,
            "TotalRecovered": 4567,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Maldives",
            "CountryCode": "MV",
            "Slug": "maldives",
            "NewConfirmed": 32,
            "TotalConfirmed": 573,
            "NewDeaths": 1,
            "TotalDeaths": 2,
            "NewRecovered": 2,
            "TotalRecovered": 20,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mali",
            "CountryCode": "ML",
            "Slug": "mali",
            "NewConfirmed": 32,
            "TotalConfirmed": 612,
            "NewDeaths": 3,
            "TotalDeaths": 32,
            "NewRecovered": 5,
            "TotalRecovered": 228,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Malta",
            "CountryCode": "MT",
            "Slug": "malta",
            "NewConfirmed": 2,
            "TotalConfirmed": 482,
            "NewDeaths": 1,
            "TotalDeaths": 5,
            "NewRecovered": 4,
            "TotalRecovered": 403,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Marshall Islands",
            "CountryCode": "MH",
            "Slug": "marshall-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Martinique",
            "CountryCode": "MQ",
            "Slug": "martinique",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mauritania",
            "CountryCode": "MR",
            "Slug": "mauritania",
            "NewConfirmed": 0,
            "TotalConfirmed": 8,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 6,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mauritius",
            "CountryCode": "MU",
            "Slug": "mauritius",
            "NewConfirmed": 0,
            "TotalConfirmed": 332,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 3,
            "TotalRecovered": 319,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mayotte",
            "CountryCode": "YT",
            "Slug": "mayotte",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mexico",
            "CountryCode": "MX",
            "Slug": "mexico",
            "NewConfirmed": 1120,
            "TotalConfirmed": 26025,
            "NewDeaths": 236,
            "TotalDeaths": 2507,
            "NewRecovered": 3363,
            "TotalRecovered": 16810,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Micronesia, Federated States of",
            "CountryCode": "FM",
            "Slug": "micronesia",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Moldova",
            "CountryCode": "MD",
            "Slug": "moldova",
            "NewConfirmed": 115,
            "TotalConfirmed": 4363,
            "NewDeaths": 4,
            "TotalDeaths": 136,
            "NewRecovered": 121,
            "TotalRecovered": 1544,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Monaco",
            "CountryCode": "MC",
            "Slug": "monaco",
            "NewConfirmed": 0,
            "TotalConfirmed": 95,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 3,
            "TotalRecovered": 81,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mongolia",
            "CountryCode": "MN",
            "Slug": "mongolia",
            "NewConfirmed": 1,
            "TotalConfirmed": 41,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 1,
            "TotalRecovered": 13,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Montenegro",
            "CountryCode": "ME",
            "Slug": "montenegro",
            "NewConfirmed": 1,
            "TotalConfirmed": 324,
            "NewDeaths": 0,
            "TotalDeaths": 8,
            "NewRecovered": 0,
            "TotalRecovered": 253,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Montserrat",
            "CountryCode": "MS",
            "Slug": "montserrat",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Morocco",
            "CountryCode": "MA",
            "Slug": "morocco",
            "NewConfirmed": 166,
            "TotalConfirmed": 5219,
            "NewDeaths": 2,
            "TotalDeaths": 181,
            "NewRecovered": 185,
            "TotalRecovered": 1838,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Mozambique",
            "CountryCode": "MZ",
            "Slug": "mozambique",
            "NewConfirmed": 1,
            "TotalConfirmed": 81,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 19,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Myanmar",
            "CountryCode": "MM",
            "Slug": "myanmar",
            "NewConfirmed": 0,
            "TotalConfirmed": 161,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 0,
            "TotalRecovered": 49,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Namibia",
            "CountryCode": "NA",
            "Slug": "namibia",
            "NewConfirmed": 0,
            "TotalConfirmed": 16,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 8,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Nauru",
            "CountryCode": "NR",
            "Slug": "nauru",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Nepal",
            "CountryCode": "NP",
            "Slug": "nepal",
            "NewConfirmed": 7,
            "TotalConfirmed": 82,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 16,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Netherlands",
            "CountryCode": "NL",
            "Slug": "netherlands",
            "NewConfirmed": 317,
            "TotalConfirmed": 41087,
            "NewDeaths": 86,
            "TotalDeaths": 5168,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Netherlands Antilles",
            "CountryCode": "AN",
            "Slug": "netherlands-antilles",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "New Caledonia",
            "CountryCode": "NC",
            "Slug": "new-caledonia",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "New Zealand",
            "CountryCode": "NZ",
            "Slug": "new-zealand",
            "NewConfirmed": 2,
            "TotalConfirmed": 1488,
            "NewDeaths": 1,
            "TotalDeaths": 21,
            "NewRecovered": 14,
            "TotalRecovered": 1316,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Nicaragua",
            "CountryCode": "NI",
            "Slug": "nicaragua",
            "NewConfirmed": 1,
            "TotalConfirmed": 16,
            "NewDeaths": 0,
            "TotalDeaths": 5,
            "NewRecovered": 0,
            "TotalRecovered": 7,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Niger",
            "CountryCode": "NE",
            "Slug": "niger",
            "NewConfirmed": 8,
            "TotalConfirmed": 763,
            "NewDeaths": 1,
            "TotalDeaths": 38,
            "NewRecovered": 9,
            "TotalRecovered": 543,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Nigeria",
            "CountryCode": "NG",
            "Slug": "nigeria",
            "NewConfirmed": 148,
            "TotalConfirmed": 2950,
            "NewDeaths": 5,
            "TotalDeaths": 98,
            "NewRecovered": 64,
            "TotalRecovered": 481,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Niue",
            "CountryCode": "NU",
            "Slug": "niue",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Norfolk Island",
            "CountryCode": "NF",
            "Slug": "norfolk-island",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Northern Mariana Islands",
            "CountryCode": "MP",
            "Slug": "northern-mariana-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Norway",
            "CountryCode": "NO",
            "Slug": "norway",
            "NewConfirmed": 51,
            "TotalConfirmed": 7955,
            "NewDeaths": 1,
            "TotalDeaths": 215,
            "NewRecovered": 0,
            "TotalRecovered": 32,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Oman",
            "CountryCode": "OM",
            "Slug": "oman",
            "NewConfirmed": 98,
            "TotalConfirmed": 2735,
            "NewDeaths": 1,
            "TotalDeaths": 13,
            "NewRecovered": 42,
            "TotalRecovered": 858,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Pakistan",
            "CountryCode": "PK",
            "Slug": "pakistan",
            "NewConfirmed": 1108,
            "TotalConfirmed": 22049,
            "NewDeaths": 38,
            "TotalDeaths": 514,
            "NewRecovered": 166,
            "TotalRecovered": 5801,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Palau",
            "CountryCode": "PW",
            "Slug": "palau",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Palestinian Territory",
            "CountryCode": "PS",
            "Slug": "palestine",
            "NewConfirmed": 9,
            "TotalConfirmed": 371,
            "NewDeaths": 0,
            "TotalDeaths": 2,
            "NewRecovered": 25,
            "TotalRecovered": 127,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Panama",
            "CountryCode": "PA",
            "Slug": "panama",
            "NewConfirmed": 326,
            "TotalConfirmed": 7523,
            "NewDeaths": 10,
            "TotalDeaths": 210,
            "NewRecovered": 182,
            "TotalRecovered": 823,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Papua New Guinea",
            "CountryCode": "PG",
            "Slug": "papua-new-guinea",
            "NewConfirmed": 0,
            "TotalConfirmed": 8,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 8,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Paraguay",
            "CountryCode": "PY",
            "Slug": "paraguay",
            "NewConfirmed": 16,
            "TotalConfirmed": 431,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 5,
            "TotalRecovered": 135,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Peru",
            "CountryCode": "PE",
            "Slug": "peru",
            "NewConfirmed": 3817,
            "TotalConfirmed": 51189,
            "NewDeaths": 100,
            "TotalDeaths": 1444,
            "NewRecovered": 986,
            "TotalRecovered": 15413,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Philippines",
            "CountryCode": "PH",
            "Slug": "philippines",
            "NewConfirmed": 199,
            "TotalConfirmed": 9684,
            "NewDeaths": 14,
            "TotalDeaths": 637,
            "NewRecovered": 93,
            "TotalRecovered": 1408,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Pitcairn",
            "CountryCode": "PN",
            "Slug": "pitcairn",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Poland",
            "CountryCode": "PL",
            "Slug": "poland",
            "NewConfirmed": 425,
            "TotalConfirmed": 14431,
            "NewDeaths": 18,
            "TotalDeaths": 716,
            "NewRecovered": 185,
            "TotalRecovered": 4280,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Portugal",
            "CountryCode": "PT",
            "Slug": "portugal",
            "NewConfirmed": 178,
            "TotalConfirmed": 25702,
            "NewDeaths": 11,
            "TotalDeaths": 1074,
            "NewRecovered": 31,
            "TotalRecovered": 1743,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Puerto Rico",
            "CountryCode": "PR",
            "Slug": "puerto-rico",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Qatar",
            "CountryCode": "QA",
            "Slug": "qatar",
            "NewConfirmed": 951,
            "TotalConfirmed": 17142,
            "NewDeaths": 0,
            "TotalDeaths": 12,
            "NewRecovered": 114,
            "TotalRecovered": 1924,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Republic of Kosovo",
            "CountryCode": "XK",
            "Slug": "kosovo",
            "NewConfirmed": 1,
            "TotalConfirmed": 856,
            "NewDeaths": 0,
            "TotalDeaths": 26,
            "NewRecovered": 87,
            "TotalRecovered": 490,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Romania",
            "CountryCode": "RO",
            "Slug": "romania",
            "NewConfirmed": 325,
            "TotalConfirmed": 13837,
            "NewDeaths": 23,
            "TotalDeaths": 841,
            "NewRecovered": 185,
            "TotalRecovered": 5454,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Russian Federation",
            "CountryCode": "RU",
            "Slug": "russia",
            "NewConfirmed": 10102,
            "TotalConfirmed": 155370,
            "NewDeaths": 95,
            "TotalDeaths": 1451,
            "NewRecovered": 1770,
            "TotalRecovered": 19865,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Rwanda",
            "CountryCode": "RW",
            "Slug": "rwanda",
            "NewConfirmed": 0,
            "TotalConfirmed": 261,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 1,
            "TotalRecovered": 129,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Réunion",
            "CountryCode": "RE",
            "Slug": "réunion",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint Helena",
            "CountryCode": "SH",
            "Slug": "saint-helena",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint Kitts and Nevis",
            "CountryCode": "KN",
            "Slug": "saint-kitts-and-nevis",
            "NewConfirmed": 0,
            "TotalConfirmed": 15,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 4,
            "TotalRecovered": 12,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint Lucia",
            "CountryCode": "LC",
            "Slug": "saint-lucia",
            "NewConfirmed": 0,
            "TotalConfirmed": 18,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 15,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint Pierre and Miquelon",
            "CountryCode": "PM",
            "Slug": "saint-pierre-and-miquelon",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint Vincent and Grenadines",
            "CountryCode": "VC",
            "Slug": "saint-vincent-and-the-grenadines",
            "NewConfirmed": 0,
            "TotalConfirmed": 17,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 9,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint-Barthélemy",
            "CountryCode": "BL",
            "Slug": "saint-barthélemy",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saint-Martin (French part)",
            "CountryCode": "MF",
            "Slug": "saint-martin-french-part",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Samoa",
            "CountryCode": "WS",
            "Slug": "samoa",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "San Marino",
            "CountryCode": "SM",
            "Slug": "san-marino",
            "NewConfirmed": 7,
            "TotalConfirmed": 589,
            "NewDeaths": 0,
            "TotalDeaths": 41,
            "NewRecovered": 6,
            "TotalRecovered": 92,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Sao Tome and Principe",
            "CountryCode": "ST",
            "Slug": "sao-tome-and-principe",
            "NewConfirmed": 151,
            "TotalConfirmed": 174,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 4,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Saudi Arabia",
            "CountryCode": "SA",
            "Slug": "saudi-arabia",
            "NewConfirmed": 1595,
            "TotalConfirmed": 30251,
            "NewDeaths": 9,
            "TotalDeaths": 200,
            "NewRecovered": 955,
            "TotalRecovered": 5431,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Senegal",
            "CountryCode": "SN",
            "Slug": "senegal",
            "NewConfirmed": 58,
            "TotalConfirmed": 1329,
            "NewDeaths": 1,
            "TotalDeaths": 11,
            "NewRecovered": 55,
            "TotalRecovered": 470,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Serbia",
            "CountryCode": "RS",
            "Slug": "serbia",
            "NewConfirmed": 120,
            "TotalConfirmed": 9677,
            "NewDeaths": 3,
            "TotalDeaths": 200,
            "NewRecovered": 149,
            "TotalRecovered": 1723,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Seychelles",
            "CountryCode": "SC",
            "Slug": "seychelles",
            "NewConfirmed": 0,
            "TotalConfirmed": 11,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 2,
            "TotalRecovered": 8,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Sierra Leone",
            "CountryCode": "SL",
            "Slug": "sierra-leone",
            "NewConfirmed": 21,
            "TotalConfirmed": 199,
            "NewDeaths": 2,
            "TotalDeaths": 11,
            "NewRecovered": 6,
            "TotalRecovered": 43,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Singapore",
            "CountryCode": "SG",
            "Slug": "singapore",
            "NewConfirmed": 632,
            "TotalConfirmed": 19410,
            "NewDeaths": 0,
            "TotalDeaths": 18,
            "NewRecovered": 62,
            "TotalRecovered": 1519,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Slovakia",
            "CountryCode": "SK",
            "Slug": "slovakia",
            "NewConfirmed": 8,
            "TotalConfirmed": 1421,
            "NewDeaths": 0,
            "TotalDeaths": 25,
            "NewRecovered": 98,
            "TotalRecovered": 741,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Slovenia",
            "CountryCode": "SI",
            "Slug": "slovenia",
            "NewConfirmed": 6,
            "TotalConfirmed": 1445,
            "NewDeaths": 1,
            "TotalDeaths": 98,
            "NewRecovered": 3,
            "TotalRecovered": 244,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Solomon Islands",
            "CountryCode": "SB",
            "Slug": "solomon-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Somalia",
            "CountryCode": "SO",
            "Slug": "somalia",
            "NewConfirmed": 79,
            "TotalConfirmed": 835,
            "NewDeaths": 3,
            "TotalDeaths": 38,
            "NewRecovered": 14,
            "TotalRecovered": 75,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "South Africa",
            "CountryCode": "ZA",
            "Slug": "south-africa",
            "NewConfirmed": 352,
            "TotalConfirmed": 7572,
            "NewDeaths": 10,
            "TotalDeaths": 148,
            "NewRecovered": 0,
            "TotalRecovered": 2746,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "South Georgia and the South Sandwich Islands",
            "CountryCode": "GS",
            "Slug": "south-georgia-and-the-south-sandwich-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "South Sudan",
            "CountryCode": "SS",
            "Slug": "south-sudan",
            "NewConfirmed": 6,
            "TotalConfirmed": 52,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Spain",
            "CountryCode": "ES",
            "Slug": "spain",
            "NewConfirmed": 1318,
            "TotalConfirmed": 219329,
            "NewDeaths": 185,
            "TotalDeaths": 25613,
            "NewRecovered": 2143,
            "TotalRecovered": 123486,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Sri Lanka",
            "CountryCode": "LK",
            "Slug": "sri-lanka",
            "NewConfirmed": 20,
            "TotalConfirmed": 771,
            "NewDeaths": 1,
            "TotalDeaths": 9,
            "NewRecovered": 19,
            "TotalRecovered": 213,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Sudan",
            "CountryCode": "SD",
            "Slug": "sudan",
            "NewConfirmed": 100,
            "TotalConfirmed": 778,
            "NewDeaths": 4,
            "TotalDeaths": 45,
            "NewRecovered": 9,
            "TotalRecovered": 70,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Suriname",
            "CountryCode": "SR",
            "Slug": "suriname",
            "NewConfirmed": 0,
            "TotalConfirmed": 10,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 9,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Svalbard and Jan Mayen Islands",
            "CountryCode": "SJ",
            "Slug": "svalbard-and-jan-mayen-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Swaziland",
            "CountryCode": "SZ",
            "Slug": "swaziland",
            "NewConfirmed": 3,
            "TotalConfirmed": 119,
            "NewDeaths": 0,
            "TotalDeaths": 1,
            "NewRecovered": 0,
            "TotalRecovered": 12,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Sweden",
            "CountryCode": "SE",
            "Slug": "sweden",
            "NewConfirmed": 495,
            "TotalConfirmed": 23216,
            "NewDeaths": 85,
            "TotalDeaths": 2854,
            "NewRecovered": 0,
            "TotalRecovered": 4074,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Switzerland",
            "CountryCode": "CH",
            "Slug": "switzerland",
            "NewConfirmed": 28,
            "TotalConfirmed": 30009,
            "NewDeaths": 11,
            "TotalDeaths": 1795,
            "NewRecovered": 200,
            "TotalRecovered": 25400,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Syrian Arab Republic (Syria)",
            "CountryCode": "SY",
            "Slug": "syria",
            "NewConfirmed": 0,
            "TotalConfirmed": 44,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 0,
            "TotalRecovered": 27,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Taiwan, Republic of China",
            "CountryCode": "TW",
            "Slug": "taiwan",
            "NewConfirmed": 0,
            "TotalConfirmed": 438,
            "NewDeaths": 0,
            "TotalDeaths": 6,
            "NewRecovered": 0,
            "TotalRecovered": 334,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Tajikistan",
            "CountryCode": "TJ",
            "Slug": "tajikistan",
            "NewConfirmed": 63,
            "TotalConfirmed": 293,
            "NewDeaths": 2,
            "TotalDeaths": 5,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Tanzania, United Republic of",
            "CountryCode": "TZ",
            "Slug": "tanzania",
            "NewConfirmed": 0,
            "TotalConfirmed": 480,
            "NewDeaths": 0,
            "TotalDeaths": 16,
            "NewRecovered": 0,
            "TotalRecovered": 167,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Thailand",
            "CountryCode": "TH",
            "Slug": "thailand",
            "NewConfirmed": 1,
            "TotalConfirmed": 2988,
            "NewDeaths": 0,
            "TotalDeaths": 54,
            "NewRecovered": 7,
            "TotalRecovered": 2747,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Timor-Leste",
            "CountryCode": "TL",
            "Slug": "timor-leste",
            "NewConfirmed": 0,
            "TotalConfirmed": 24,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 20,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Togo",
            "CountryCode": "TG",
            "Slug": "togo",
            "NewConfirmed": 2,
            "TotalConfirmed": 128,
            "NewDeaths": 0,
            "TotalDeaths": 9,
            "NewRecovered": 0,
            "TotalRecovered": 74,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Tokelau",
            "CountryCode": "TK",
            "Slug": "tokelau",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Tonga",
            "CountryCode": "TO",
            "Slug": "tonga",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Trinidad and Tobago",
            "CountryCode": "TT",
            "Slug": "trinidad-and-tobago",
            "NewConfirmed": 0,
            "TotalConfirmed": 116,
            "NewDeaths": 0,
            "TotalDeaths": 8,
            "NewRecovered": 3,
            "TotalRecovered": 102,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Tunisia",
            "CountryCode": "TN",
            "Slug": "tunisia",
            "NewConfirmed": 4,
            "TotalConfirmed": 1022,
            "NewDeaths": 0,
            "TotalDeaths": 43,
            "NewRecovered": 76,
            "TotalRecovered": 482,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Turkey",
            "CountryCode": "TR",
            "Slug": "turkey",
            "NewConfirmed": 1832,
            "TotalConfirmed": 129491,
            "NewDeaths": 59,
            "TotalDeaths": 3520,
            "NewRecovered": 5119,
            "TotalRecovered": 73285,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Turkmenistan",
            "CountryCode": "TM",
            "Slug": "turkmenistan",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Turks and Caicos Islands",
            "CountryCode": "TC",
            "Slug": "turks-and-caicos-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Tuvalu",
            "CountryCode": "TV",
            "Slug": "tuvalu",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "US Minor Outlying Islands",
            "CountryCode": "UM",
            "Slug": "us-minor-outlying-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Uganda",
            "CountryCode": "UG",
            "Slug": "uganda",
            "NewConfirmed": 1,
            "TotalConfirmed": 98,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 55,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Ukraine",
            "CountryCode": "UA",
            "Slug": "ukraine",
            "NewConfirmed": 366,
            "TotalConfirmed": 12697,
            "NewDeaths": 13,
            "TotalDeaths": 316,
            "NewRecovered": 256,
            "TotalRecovered": 1875,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "United Arab Emirates",
            "CountryCode": "AE",
            "Slug": "united-arab-emirates",
            "NewConfirmed": 462,
            "TotalConfirmed": 15192,
            "NewDeaths": 9,
            "TotalDeaths": 146,
            "NewRecovered": 187,
            "TotalRecovered": 3153,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "United Kingdom",
            "CountryCode": "GB",
            "Slug": "united-kingdom",
            "NewConfirmed": 4406,
            "TotalConfirmed": 194990,
            "NewDeaths": 693,
            "TotalDeaths": 29427,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "United States of America",
            "CountryCode": "US",
            "Slug": "united-states",
            "NewConfirmed": 23517,
            "TotalConfirmed": 1203892,
            "NewDeaths": 2121,
            "TotalDeaths": 71043,
            "NewRecovered": 0,
            "TotalRecovered": 187180,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Uruguay",
            "CountryCode": "UY",
            "Slug": "uruguay",
            "NewConfirmed": 13,
            "TotalConfirmed": 670,
            "NewDeaths": 0,
            "TotalDeaths": 17,
            "NewRecovered": 21,
            "TotalRecovered": 468,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Uzbekistan",
            "CountryCode": "UZ",
            "Slug": "uzbekistan",
            "NewConfirmed": 18,
            "TotalConfirmed": 2207,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 96,
            "TotalRecovered": 1501,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Vanuatu",
            "CountryCode": "VU",
            "Slug": "vanuatu",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Venezuela (Bolivarian Republic)",
            "CountryCode": "VE",
            "Slug": "venezuela",
            "NewConfirmed": 4,
            "TotalConfirmed": 361,
            "NewDeaths": 0,
            "TotalDeaths": 10,
            "NewRecovered": 0,
            "TotalRecovered": 158,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Viet Nam",
            "CountryCode": "VN",
            "Slug": "vietnam",
            "NewConfirmed": 0,
            "TotalConfirmed": 271,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 13,
            "TotalRecovered": 232,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Virgin Islands, US",
            "CountryCode": "VI",
            "Slug": "virgin-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Wallis and Futuna Islands",
            "CountryCode": "WF",
            "Slug": "wallis-and-futuna-islands",
            "NewConfirmed": 0,
            "TotalConfirmed": 0,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 0,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Western Sahara",
            "CountryCode": "EH",
            "Slug": "western-sahara",
            "NewConfirmed": 0,
            "TotalConfirmed": 6,
            "NewDeaths": 0,
            "TotalDeaths": 0,
            "NewRecovered": 0,
            "TotalRecovered": 5,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Yemen",
            "CountryCode": "YE",
            "Slug": "yemen",
            "NewConfirmed": 10,
            "TotalConfirmed": 22,
            "NewDeaths": 2,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 1,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Zambia",
            "CountryCode": "ZM",
            "Slug": "zambia",
            "NewConfirmed": 1,
            "TotalConfirmed": 138,
            "NewDeaths": 0,
            "TotalDeaths": 3,
            "NewRecovered": 14,
            "TotalRecovered": 92,
            "Date": "2020-05-06T04:27:52Z"
        },
        {
            "Country": "Zimbabwe",
            "CountryCode": "ZW",
            "Slug": "zimbabwe",
            "NewConfirmed": 0,
            "TotalConfirmed": 34,
            "NewDeaths": 0,
            "TotalDeaths": 4,
            "NewRecovered": 0,
            "TotalRecovered": 5,
            "Date": "2020-05-06T04:27:52Z"
        }
    ],
    "Date": "2020-05-06T04:27:52Z"
 }
